add more echo statements for debugging

diff --git a/.github/workflows/merge-upstream.yml b/.github/workflows/merge-upstream.yml
--- a/.github/workflows/merge-upstream.yml
+++ b/.github/workflows/merge-upstream.yml
@@ -75,7 +75,22 @@ jobs:
           echo "### Associated pull request" >> $GITHUB_STEP_SUMMARY
           echo "$PR_URL" >> $GITHUB_STEP_SUMMARY
 
-          sleep 20s
+          # wait for required checks to be available (up to 15 tries, with 3s wait between tries)
+          for i in {1..15}; do
+            gh pr checks $PR_URL --required 2>&1
+            CHECK_OUTPUT=$(gh pr checks $PR_URL --required 2>&1)
+            echo "Output from 'gh pr checks': $CHECK_OUTPUT"
+
+            if [[ "$CHECK_OUTPUT" =~ ^no(\ required)?\ checks\ reported.* ]]; then
+              if [ $i -eq 15 ]; then exit 1; fi
+              echo "Required checks are not yet available. Waiting for 3s and trying again."
+              sleep 3s
+              continue
+            fi
+
+            break
+          done
+          
           gh pr checks "$PR_URL" --required --watch
 
           if [ $? -ne 0 ]; then
