Add logic to wait for required checks to be available on PR

diff --git a/.github/workflows/merge-upstream.yml b/.github/workflows/merge-upstream.yml
--- a/.github/workflows/merge-upstream.yml
+++ b/.github/workflows/merge-upstream.yml
@@ -78,7 +78,19 @@ jobs:
           echo "$PR_URL" >> $GITHUB_STEP_SUMMARY
           echo "`$PR_URL`" >> $GITHUB_STEP_SUMMARY
 
-          sleep 20s
+          # wait for required checks to be available (up to 15 tries, with 3s wait between tries)
+          for i in {1..15}; do
+            CHECK_OUTPUT=$(gh pr checks "$PR_URL" --required 2>&1)
+            if [[ "$CHECK_OUTPUT" =~ ^no(\ required)?\ checks\ reported.* ]]; then
+              if [ $i -eq 15 ]; then exit 1; fi
+              echo "Required checks are not yet available. Waiting for 3s and trying again."
+              sleep 3s
+              continue
+            fi
+
+            break
+          done
+          
           gh pr checks "$PR_URL" --required --watch
 
       - name: Merge (fast-forward)
